@startuml 
state Configuring {
Gestor -> Maquina : controla

Maquina -> Dinero : maneja
Maquina -> Producto : vende

Dinero -> Billete : contiene
Dinero -> Moneda : contiene

Producto -> Dinero: cuesta
}
@enduml
