@startuml
state Programa{
  
Gestor -> Maquina : controla

Maquina ---> Billete : totalBilletes()
Maquina ---> Moneda : totalMonedas()
Maquina --> Producto : totalProductos()

Dinero --> Billete : actualizarPrecio()
Dinero --> Billete : actualizarCantidad()
Dinero --> Moneda : actualizarPrecio()
Dinero --> Moneda : actualizarCantidad()

Producto -> Dinero: cuesta

}
@enduml
