@startuml Objetos
object "batalla : Batalla" as Batalla

object "mago : Heroe" as Heroe
object "vampiresa : Enemigo" as Enemigo

object "baston : Arma" as ArmaH1
object "libro : Arma" as ArmaH2

object "arma1 : Arma" as ArmaV1
object "arma2 : Arma" as ArmaV2

object "vista : VistaBatalla" as VistaBatalla

Batalla -l- VistaBatalla

Enemigo -u- Batalla : Participa en <
Heroe -u- Batalla : Participa en <

Heroe -d- ArmaH1 : Utiliza <
Heroe -d- ArmaH2 : Utiliza <

Enemigo -d- ArmaV1 : Utiliza <
Enemigo -d- ArmaV2 : Utiliza <


@enduml