@startuml modelo-de-dominio
class Maquina
class Billete
class Moneda
class Producto
class Dinero
class Mantenimiento

Maquina *--r Mantenimiento
Maquina o--l Dinero
Maquina o--- Producto

Dinero *--- Billete
Dinero *--- Moneda

@enduml
