@startuml modelo-de-dominio
class Maquina
class Billete
class Moneda
class Producto
class Dinero
class Mantenimiento

Maquina *--l Mantenimiento
Maquina o-- Dinero
Maquina o--- Producto

Dinero *--- Billete
Dinero *--- Moneda

Mantenimiento ...r.o Dinero
@enduml