@startuml objetos

object "Maquina: Maquina001" as maq1{
nombre = "Maquina001"
billetes = [10, 5]
monedas = [2, 0,5]
productos = [Galletas]
}

object "Mantenimiento: Mantenimiento001" as man1{
}

object "Dinero" as dinero{
valor
cantidad
}

object "Billete: €10" as b10{
valor = 10
cantidad = 12
}

object "Billete: €5" as b5{
valor = 5
cantidad = 5
}

object "Moneda: €2" as m2{
valor = 2
cantidad = 8
}

object "Moneda: €0,5" as m05{
valor = 0,5
cantidad = 4
}

object "Producto: Galletas" as pro1{
valor = 1,4
cantidad = 12
}

maq1 --r man1 
maq1 -l- pro1

dinero <|--- b10
dinero <|--- b5
dinero <|--- m2
dinero <|--- m05

maq1 --- b10
maq1 --- b5
maq1 --- m2
maq1 --- m05
@enduml
