@startuml modelo-de-dominio
class Compra {
    + descripcion
    + fechaDeCompra

    + Compra()
    + realizarCompra()
    + menu(List<Maquina> maquinas)
}

class Maquina {
    + nombre
    + Billetes[]
    + Monedas[]
    + Productos[]

    + Maquina(String nombre, List<Billete> billetes, List<Moneda> monedas, List<Producto> productos)
    + totalBilletes()
    + totalMonedas()
    + totalProductos()
    + menu(Scanner scanner)
    + agregar(Scanner scanner, List<Maquina> maquinas)

}

class Billete {
    + valor
    + cantidad

    + Billete(double valor, int cantidad)
    + menu(Scanner scanner)
    + agregar(Scanner scanner, List<Billete> billetes)
}

class Moneda {
    + valor
    + cantidad

    + Moneda(double valor, int cantidad)
    + menu(Scanner scanner)
    + agregar(Scanner scanner, List<Moneda> monedas)
}

class Producto {
    + nombre
    + precio
    + cantidad

    + Producto(String nombre, double precio, int cantidad)
    + actualizarPrecio(double precio)
    + actualizarNombre(String nombre)
    + actualizarCantidad(int cantidad)
    + menu(Scanner scanner)
    + agregar(Scanner scanner, List<Producto> productos)
}

class Dinero {
    + valor
    + cantidad

    + Dinero(double valor, int cantidad)
}

class Mantenimiento {
    + nombre
    + tipo

    + Mantenimiento()
    + generarReposicion()
}

Maquina -u-o Compra
Maquina *--l Mantenimiento
Maquina o---r Producto
Maquina o--- Billete
Maquina o--- Moneda

Dinero <|--- Billete
Dinero <|--- Moneda

@enduml