@startuml modelo-de-dominio
class Compra {
    - id
    + nombre
    + descripcion
    + fechaDeCompra

    + Compra()
    + realizarCompra()
}

class Maquina {
    - id
    + nombre
    + Dinero[]
    + Productos[]

    + Maquina()
    + totalDinero()
    + totalProductos()

}

class Billete {
    - id
    + nombre
    + valor
    + moneda

    + Billete()
}

class Moneda {
    - id
    + nombre
    + valor
    + moneda

    + Moneda()
}

class Producto {
    - id
    + nombre
    + precio
    + proveedor

    + Producto()
}

class Dinero {
    - id
    + nombre

    + Dinero()
}

class Mantenimiento  {
    - id
    + nombre
    + tipo

    + Mantenimiento()
    + generarReposicion()
}

Maquina -u-o Compra
Maquina *--l Mantenimiento
Maquina o-- Dinero
Maquina o---r Producto

Dinero *--- Billete
Dinero *--- Moneda
Mantenimiento ...r.o Dinero

@enduml