@startuml modeloDelDominio

class Persona {
    - Planta plantaActual
    - Planta plantaDestino
    - Tiempo tiempoEnDestino
    - boolean esperandoAscensor
    - boolean dentroAscensor
    - Tiempo elegirTiempoEnDestino()
    - Planta elegirPlantaDestino()
    # void mover()
    + Planta getPlantaActual()
    + Planta getPlantaDestino()
    + boolean estadoEsperandoAscensor()
    + void setPlantaActual(Planta plantaActual)
    + void setPlantaDestino(Planta plantaDestino)
    + void esperar Ascensor()
    + void entrarAscensor()
    + void salirAscensor()

}

enum "structures.enums.EstadoAscensor" {
    SUBIENDO
    BAJANDO
    PARADO
}

class Tiempo {
    - int horas
    - int minutos
    - int segundos 
    - Universidad universidad
    + void incremenrtar()
    + void disminuir()
    + int getHoras()
    + int getMinutos()
    + int getSegundos()
    + Universidad getUniversidad()
    - void empezar()
    + {static} void main(String[] args)

}


class Planta {
    - int nivel
    - ArrayList<Persona> personasEnPlanta
    + void agregarPersona(Persona persona)
    + void eliminarPersona(Persona persona)
    + void mover(Ascensor ascensor)
    + int getNivel()
    + ArrayList<Persona> getPersonasEsperandoAscensor()
    + void setNivel(int nivel)
    + int compareTo(Planta o)

}


class Ascensor {
    - int idAscensor
    - int nivel
    - ArrayList<Planta> plantas
    - ArrayList<Persona> personas
    - EstadoAscensor estado
    + void agregarPersona(Persona persona)
    + void eliminarPersona(Persona persona)
    # void mover()
    + Planta getPlantaActual()
    + int getPersonasEnAscensor()
    + boolean estaVacio()
    + boolean estaLleno()
    + boolean estaSubiendo()
    + boolean estaBajando()
    + boolean estaParado()
    - void Bajarpersona()
    + void llamar(persona persona)
    + void subir()
    + void bajar()
}


class Universidad {
    - ArrayList<Planta> plantas
    - Map<int, Ascensor> ascensores
    - void crearPlantas()
    # void configurarAscensores()
    + ArrayList<Planta> getPlantas()
    + Map<Integer,Ascensor> getAscensores()
    + boolean llegoUnaPersona()
    # void mover()
}

Ascensor *--d Persona 
Ascensor *-u Planta 
Ascensor *- "structures.enums.EstadoAscensor" 
Universidad *- Ascensor 
Universidad *- Planta 
Universidad *- Persona 
Planta *--d Persona 
Persona *--d Tiempo 


 

@enduml