@startuml diagramaDeEstados

State Ascensor{
    State Parado
    State Subiendo
    State Bajando

    Parado --> Subiendo : Subir
    Parado --> Bajando : Bajar
    Subiendo --> Parado : Parar
    Bajando --> Parado : Parar
}

@enduml