@startuml modeloDelDominio

class Persona {

}

enum "structures.enums.EstadoAscensor" {
}

class Tiempo {
}


class Planta {
}


class Ascensor {
}


class Universidad {

}

Ascensor *--d Persona 
Ascensor *-u Planta 
Ascensor *- "structures.enums.EstadoAscensor" 
Universidad *- Ascensor 
Universidad *- Planta 
Universidad *- Persona 
Planta *--d Persona 
Persona *--d Tiempo 


 

@enduml