@startuml modeloDelDominio

class Persona
class Tiempo
class Planta
class Ascensor
class Universidad

Planta -u-o Persona 
Ascensor o-u- Persona 
Planta *-u- Ascensor 
Ascensor .r.. Tiempo 

Planta -u-* Universidad 
Ascensor -u-* Universidad
Persona -u-o Universidad 

Persona ... Tiempo

@enduml